### ISSUE TITLE
Add induction safety verification 

### ISSUE THREAD

**Issue by AnotherMatt92** [swindonmakers/AccessSystem#31]
when someone has been inducted and use the /induct Name on Tool. It should then message the person (if assosiated with telegram) and asks them if they are happy with the induction and that they feel safe to use the tool with a yes/no answer

**Comment by castaway** [comment]
We can also email people if they're not identified with telegram yet.. 

This sounds like: 
* Add a new field for "pending acceptance" (in the allowed table)
* Change /induct <member> on <tool> to create the row, and set "pending acceptance" to true
* Send a telegram message or email to inductee with a button/link which sets "pending acceptance" to false
* Change various "display" commands, eg "/inducted_on" to check the new field (and display what?)

**Comment by castaway** [comment]
* Delete/remove the induction if not accepted after.. some length of time?
* Get acceptances for existing inductions? (Piles of emails, or better a one-off per valid member / not long expired member with list of tools)

**Comment by castaway** [comment]
done
