### ISSUE TITLE
Error on /whois failure is confusing

### ISSUE THREAD

**Issue by theorbtwo** [swindonmakers/AccessSystem#59]
https://github.com/swindonmakers/AccessSystem/blob/fd4bf910ffb512ec72f7683b9af2f29a0165bd68/lib/AccessSystem/TelegramBot.pm#L424

The /whois command should give different results for "I cannot find any matching people", vs "I cannot parse the command".

**Comment by castaway** [comment]
Looks like we fixed this at some point.. it says I cant find a member with that name, or "Try /whois .. "
