### ISSUE TITLE
Consider switching to fork of Barclayscrape

### ISSUE THREAD

**Issue by oestoer** [swindonmakers/AccessSystem#61]
The original repo (https://github.com/russss/barclayscrape) that pulls transactions from the Barclays bank account is archived and has not been updated since Feb 5, 2023. There's a fork that is still maintained: https://github.com/carpii/barclayscrape

**Comment by castaway** [comment]
```
castaway@insel /usr/src/extern/barclayscrape $ git remote -v
carpii  git@github.com:carpii/barclayscrape.git (fetch)
carpii  git@github.com:carpii/barclayscrape.git (push)
castaway        git@github.com:castaway/barclayscrape.git (fetch)
castaway        git@github.com:castaway/barclayscrape.git (push)
origin  https://github.com/russss/barclayscrape (fetch)
origin  https://github.com/russss/barclayscrape (push)
```

already using it ;)

**Comment by oestoer** [comment]
okay, thanks for checking, I'll update the readme then, as that doesn't reflect this
