### ISSUE TITLE
Remove Forum

### ISSUE THREAD

**Issue by oestoer** [swindonmakers/AccessSystem#89]
The link from the website had been removed.
The [forum](https://forum.swindon-makerspace.org/) itself is still live.
Backup content into an archive (could be stored on Google Drive)
Remove subdomain.
Remove forum from https://github.com/swindonmakers/uptime-monitor

**Comment by castaway** [comment]
@M1XZG created the uptime thingy, I assume it needs reconfiguring.

**Comment by castaway** [comment]
DNS subdomain deleted

**Comment by M1XZG** [comment]
The forums have been removed from https://github.com/swindonmakers/uptime-monitor/blob/master/.upptimerc.yml

**Comment by castaway** [comment]
Sounds like done to me
