### ISSUE TITLE
Tool pending members can activate tool

### ISSUE THREAD

**Issue by AnotherMatt92** [swindonmakers/AccessSystem#94]
When a member is inducted their status is set to "inducted (pending)", the pending status is removed when they click the link in the email. 
While in pending state they should not have access to the tool. However right now they do

**Comment by AnotherMatt92** [comment]
Beware that with the current bug where members have "the door" pending that if that is not fixed may cause paying members being denied entry to the space as they dont have permission to open a door

**Comment by castaway** [comment]
> Beware that with the current bug where members have "the door" pending that if that is not fixed may cause paying members being denied entry to the space as they dont have permission to open a door

This part was fixed in #90
